name: Build and Push Docker Image test                                                                
                                                                                                      
on:                                                                                                   
  workflow_dispatch:
jobs:           
  client:                                                                                             
    name: Client                                                                                      
    runs-on: ubuntu-latest                                                                            
                                                                                                      
    steps:                                                                                            
      - name: Checkout the repository                                                                 
        uses: actions/checkout@v3.0.2                                                                 
                                                                                                      
      - name: Login to GitHub Container Registry                                                      
        uses: docker/login-action@v2.0.0                                                              
        with:                                                                                         
          registry: ghcr.io                                                                           
          username: ${{ github.repository_owner }}                                                    
          password: ${{ secrets.CR_PAT }}                                                             
                                                                                                      
      - name: Set up QEMU                                                                             
        uses: docker/setup-qemu-action@v1                                                             
      - name: Set up Docker Buildx                                                                    
        uses: docker/setup-buildx-action@v1                                                           
      - name: Build and Push Client Image                                                             
        uses: docker/build-push-action@v3.1.1                                                         
        with:                                                                                         
          context: .     
          push: true     
          platforms: linux/amd64, linux/arm64
          file: client/Dockerfile
          tags: |
            ghcr.io/kbc8894/reactive-resume:client-test
  
      
  server:
    name: Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.0.2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and Push Server Image
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          file: server/Dockerfile
          tags: |
            ghcr.io/kbc8894/reactive-resume:server-test

